services:
  api:
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./src:/app/src
    expose:
      - 8000
    networks:
      - app-network

  frontend:
    image: frontend
    env_file:
      - "./frontend/.env.production"
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge