version: "3.8"

services:
  api:
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./models:/usr/local/app/models
      - ./src:/usr/local/app/src